version: '3'

services:
  nginx:
    image: nginx:mainline-alpine3.18-slim
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nodenet
    depends_on:
      - app

  app:
    build: 
      context: node
    container_name: app
    command: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - nodenet
    tty: true
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db/init-scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge